# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 09:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Defenition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, null=True)),
                ('defenition', models.TextField(default=b'')),
                ('example', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200, null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='defenition',
            name='synonyms',
            field=models.ManyToManyField(related_name='synonyms', to='dictionary.Word'),
        ),
        migrations.AddField(
            model_name='defenition',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.Word'),
        ),
    ]
