# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defenition',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defenition', to='dictionary.Word'),
        ),
    ]
