# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_auto_20160702_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='defenition',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
