# Generated by Django 2.1.7 on 2019-02-21 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_defenition_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defenition',
            name='defenition',
            field=models.TextField(default=''),
        ),
    ]
