# Generated by Django 2.1.7 on 2019-03-02 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0004_auto_20190221_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='defenition',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dictionary/images'),
        ),
    ]
