# Generated by Django 2.1.7 on 2019-03-02 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0005_defenition_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='pronunciation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
