# Generated by Django 2.1.7 on 2019-03-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0006_word_pronunciation'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='tmp_checked',
            field=models.BooleanField(default=False),
        ),
    ]
