# Generated by Django 2.1.7 on 2019-03-29 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0009_auto_20190323_2059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='defenition',
            options={'verbose_name': 'Definition', 'verbose_name_plural': 'Definitions'},
        ),
        migrations.AddField(
            model_name='defenition',
            name='image_approved',
            field=models.BooleanField(default=False),
        ),
    ]
