---

- name: 'Provision {{ application_name }}'
  hosts: gcp
  gather_facts: no
  sudo: yes
  sudo_user: root
  remote_user: '{{ remote_user }}'

  vars:
    - deploy_env: gcp
    - application_name: owlbot
    - set_up_application_user: yes
    - application_user: owlbot
    - application_group: sites
    - update_apt_cache: yes
    - django_settings_file: 'app.core.settings.gcp'
    - requirements_file: '{{ git_root }}/requirements.txt'
    - virtualenv_path: '/sites/{{ application_name }}'
    - django_dir: "{{ git_root }}" #  Location of manage.py
    - run_django_collectstatic: yes

  vars_files:
    - vars/db.yml
    - vars/web.yml
    - vault/secrets.yml

  roles:
    - base
    - db
    - web

...